version: '3.1'
services:
  typescript:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - PING_LISTEN_PORT=80
  typescript2:
    build: 
      context: .
      dockerfile: Dockerfile.2
    ports:
      - "8080:8080"
    environment:
      - PING_LISTEN_PORT=8080